# Site settings
title: Daniel Penalva (uiuran penalvadguardthesilence! penalvelho penalvinha)
email: dkajah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog about AI Deep Learning Language and Algorithmic Affairs, find someone to love hope you are doing good
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uiuran.github.io" # the base hostname & protocol for your site
author: Daniel Penalva
twitter_username: dpen
facebook_username: daniel.penalva.7583
github_username: uiuran
irc_channel: labmacambira 

social:
    name: Daniel Penalva
    links:
        - https://github.com/uiuran
        - https://www.facebook.com/daniel.penalva.7583

# Build settings
markdown: kramdown
timezone: America/Sao_Paulo

# for search engine optimization
plugins_dir:
      - jekyll-seo-tag

plugins:
   - jekyll-seo-tag
